name: Install CF CLI
on: [push]

jobs:
  install-cf-cli:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Check OS Type
        run: echo "Running on $(uname -s)"

      - name: Install CF CLI on Ubuntu
        if: runner.os == 'Linux'
        run: |
          curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&source=github&version=v6" | tar -zx
          mv cf /usr/local/bin
          cf version

      - name: Install CF CLI on macOS
        if: runner.os == 'macOS'
        run: |
          curl -L "https://packages.cloudfoundry.org/stable?release=macosx64-binary&source=github&version=v6" | tar -zx
          mv cf /usr/local/bin
          cf version


      - name: Verify Installation
        run: cf --version
