name: Install Cloud Foundry CLI

on:
  push:
    branches:
      - main

jobs:
  install-cf-cli:
    runs-on: macos-latest

    steps:
    - name: Install Homebrew
      run: |
       if ! command -v brew &> /dev/null; then
       echo " Homebrew not found. Installing Homebrew "
       /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
       else
       echo " Homebrew is already installed"
       fi

    - name: Install Cloud Foundry CLI
      run: |
       brew install cloudfoundry/tap/cf-cli@6
       cf --version
